/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConversationRouteImport } from './routes/conversation'
import { Route as GrammarRouteImport } from './routes/grammar'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as SpeakRouteImport } from './routes/speak'
import { Route as TranslateRouteImport } from './routes/translate'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as TutorIndexRouteImport } from './routes/tutor.index'
import { Route as TutorThreadIdRouteImport } from './routes/tutor.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationRoute = ConversationRouteImport.update({
  id: '/conversation',
  path: '/conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarRoute = GrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakRoute = SpeakRouteImport.update({
  id: '/speak',
  path: '/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateRoute = TranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorIndexRoute = TutorIndexRouteImport.update({
  id: '/tutor/',
  path: '/tutor/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorThreadIdRoute = TutorThreadIdRouteImport.update({
  id: '/tutor/$threadId',
  path: '/tutor/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/conversation': typeof ConversationRoute
  '/grammar': typeof GrammarRoute
  '/insights': typeof InsightsRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/quiz': typeof QuizRoute
  '/speak': typeof SpeakRoute
  '/translate': typeof TranslateRoute
  '/vocabulary': typeof VocabularyRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/tutor/$threadId': typeof TutorThreadIdRoute
  '/tutor/': typeof TutorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/conversation': typeof ConversationRoute
  '/grammar': typeof GrammarRoute
  '/insights': typeof InsightsRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/quiz': typeof QuizRoute
  '/speak': typeof SpeakRoute
  '/translate': typeof TranslateRoute
  '/vocabulary': typeof VocabularyRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/tutor/$threadId': typeof TutorThreadIdRoute
  '/tutor': typeof TutorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/conversation': typeof ConversationRoute
  '/grammar': typeof GrammarRoute
  '/insights': typeof InsightsRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/quiz': typeof QuizRoute
  '/speak': typeof SpeakRoute
  '/translate': typeof TranslateRoute
  '/vocabulary': typeof VocabularyRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/tutor/$threadId': typeof TutorThreadIdRoute
  '/tutor/': typeof TutorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/conversation'
    | '/grammar'
    | '/insights'
    | '/privacy'
    | '/progress'
    | '/quiz'
    | '/speak'
    | '/translate'
    | '/vocabulary'
    | '/api/chat'
    | '/api/transcribe'
    | '/tutor/$threadId'
    | '/tutor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/conversation'
    | '/grammar'
    | '/insights'
    | '/privacy'
    | '/progress'
    | '/quiz'
    | '/speak'
    | '/translate'
    | '/vocabulary'
    | '/api/chat'
    | '/api/transcribe'
    | '/tutor/$threadId'
    | '/tutor'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/conversation'
    | '/grammar'
    | '/insights'
    | '/privacy'
    | '/progress'
    | '/quiz'
    | '/speak'
    | '/translate'
    | '/vocabulary'
    | '/api/chat'
    | '/api/transcribe'
    | '/tutor/$threadId'
    | '/tutor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  ConversationRoute: typeof ConversationRoute
  GrammarRoute: typeof GrammarRoute
  InsightsRoute: typeof InsightsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgressRoute: typeof ProgressRoute
  QuizRoute: typeof QuizRoute
  SpeakRoute: typeof SpeakRoute
  TranslateRoute: typeof TranslateRoute
  VocabularyRoute: typeof VocabularyRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  TutorThreadIdRoute: typeof TutorThreadIdRoute
  TutorIndexRoute: typeof TutorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation': {
      id: '/conversation'
      path: '/conversation'
      fullPath: '/conversation'
      preLoaderRoute: typeof ConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar': {
      id: '/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof GrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speak': {
      id: '/speak'
      path: '/speak'
      fullPath: '/speak'
      preLoaderRoute: typeof SpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate': {
      id: '/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof TranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/': {
      id: '/tutor/'
      path: '/tutor'
      fullPath: '/tutor/'
      preLoaderRoute: typeof TutorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/$threadId': {
      id: '/tutor/$threadId'
      path: '/tutor/$threadId'
      fullPath: '/tutor/$threadId'
      preLoaderRoute: typeof TutorThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  ConversationRoute: ConversationRoute,
  GrammarRoute: GrammarRoute,
  InsightsRoute: InsightsRoute,
  PrivacyRoute: PrivacyRoute,
  ProgressRoute: ProgressRoute,
  QuizRoute: QuizRoute,
  SpeakRoute: SpeakRoute,
  TranslateRoute: TranslateRoute,
  VocabularyRoute: VocabularyRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  TutorThreadIdRoute: TutorThreadIdRoute,
  TutorIndexRoute: TutorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
